import { createContext, useContext, useState } from 'react'

const translations = {
  en: {
    home: 'Home',
    about: 'About',
    products: 'Products',
    contact: 'Contact',
    welcome: 'Welcome to Mieyeifie',
    tagline: 'Pure, Healthy and Refreshing Water for Every Occasion',
    explore: 'Explore Products',
    aboutUs: 'About Us',
    whoWeAre: 'Who We Are',
    whoWeAreText1: 'We are a passionate team dedicated to delivering excellence in every product we create. With a strong foundation built on quality and trust, we continue to grow while staying true to our core values.',
    whoWeAreText2: 'Our journey has been shaped by innovation, hard work, and a deep commitment to our clients.',
    ourMission: 'Our Mission',
    ourMissionText1: 'Our mission is to provide outstanding products and services that exceed expectations. We believe in building long-term relationships through integrity, transparency, and consistent quality.',
    ourMissionText2: 'Every project we take on is an opportunity to create something meaningful and lasting.',
    meetManagement: 'Meet The Management',
    ourProducts: 'Our Products',
    perItem: 'per item',
    wholesale: 'Wholesale',
    wholesaleText: 'If you want to buy in wholesale, click here to get special pricing and bulk options.',
    bagsProduced: 'Bags of water produced daily',
    packsProduced: 'Packs of ozonized water produced',
    deliveryCoverage: 'Of Bayelsa State covered delivery-wise',
    becomeDealer: 'Become a Dealer',
    requirements: 'Requirements',
    benefits: 'Benefits',
    dealerApplication: 'Dealer Application',
    fullName: 'Full Name',
    phoneNumber: 'Phone Number',
    emailAddress: 'Email Address',
    businessLocation: 'Business Location / City',
    yearsExperience: 'Years of Business Experience',
    aboutYourself: 'Tell us a bit about yourself or your business...',
    submitApplication: 'Submit Application',
    contactUs: 'Contact Us',
    sendMessage: 'Send a Message',
    yourName: 'Your Name',
    subject: 'Subject',
    yourMessage: 'Your Message...',
    connectWithUs: 'Connect With Us',
    callUs: 'Call Us',
    ourLocations: 'Our Locations',
    factoryOutlet: 'Factory & Outlet Locations',
    quickLinks: 'Quick Links',
    followUs: 'Follow Us',
    allRights: 'All rights reserved.',
    req1: 'Must be at least 21 years old',
    req2: 'Valid means of identification',
    req3: 'Proven business location or storefront',
    req4: 'Ability to make initial product purchase',
    req5: 'Good understanding of the local market',
    req6: 'Commitment to quality and customer service',
    ben1: 'Competitive wholesale pricing',
    ben2: 'Marketing and branding support',
    ben3: 'Reliable product supply',
    ben4: 'Training and business guidance',
    ben5: 'Exclusive territory opportunities'
  },
  ij: {
    home: 'Wári',
    about: 'Ebi-kẹmẹ Tari / Ọgbọ',
    products: 'Ẹẹ/Yamọ-ẹẹ',
    contact: 'Izon-ẹẹ / Wari-gbe',
    welcome: 'Kọ̀-nua, mie-ye-fie wári',
    tagline: 'Dirimọ, Ẹbi, ba Dirimo Béné-Amẹ Kọmụ Fịẹ Wári Dirimọ',
    explore: 'Yamọ-ẹẹ Mọ́ Fịẹ',
    aboutUs: 'Wai / Wọi Paá-ẹẹ',
    whoWeAre: 'Wọi Kẹmẹ Mọ́-ẹ',
    whoWeAreText1: 'Wọi fịẹ, taridịmọ emi ẹẹ mie kẹmẹ kẹ́mẹ́ pádịmọ-ẹẹ. Wọi ẹbị-ẹẹ mọ wari pádịmọ, bẹ́lẹ kọ́mụ titi emi.',
    whoWeAreText2: 'Wọ́i dẹi dẹi pá-ẹẹ, karidịmọ, bọlọu-yé-mie, ba kẹmẹ taridịmọ pádịmọ kẹmẹ.',
    ourMission: 'Wọi-yé-Mie-Karia',
    ourMissionText1: 'Wọi-karia ẹbi-ẹẹ mie, ba kẹmẹ ẹbị mọ tari dịmọ. Wọi fịẹ, kẹmẹ taridịmọ ba karia-yé mie.',
    ourMissionText2: 'Mie yé kẹ́mẹ́ ẹbị mọ bọlọu wári mie dẹ́.',
    meetManagement: 'Wári Bọlọu Kẹmẹ Mọ́ Dịrị',
    ourProducts: 'Wọi Yamọ-ẹẹ',
    perItem: 'keni yamọ-ẹẹ',
    wholesale: 'Púgụ-yama / Bálá',
    wholesaleText: 'Iya bálá-mọ yamọ fịẹ mọ, ẹẹ nua mọ kẹkẹ, bọ́lọu karia gbe.',
    bagsProduced: 'Keni kẹni amẹ-baga mọ mie tinin',
    packsProduced: 'Keni kẹni ozonized amẹ-pack mọ mie tinin',
    deliveryCoverage: 'Bayelsa State kẹmẹ kẹ́mẹ́ gbe-ẹẹ',
    becomeDealer: 'Dẹrẹ Kẹmẹ Mie',
    requirements: 'Fịẹ-yẹ-ẹẹ',
    benefits: 'Ẹbi-yẹ-ẹẹ',
    dealerApplication: 'Dẹrẹ-kẹmẹ Karia Dịrị',
    fullName: 'Iya Ére Kọmụ',
    phoneNumber: 'Fọn Númba',
    emailAddress: 'Email Address',
    businessLocation: 'Yẹ-Mie-Ama / Wári',
    yearsExperience: 'Yẹ-Mie-Éréba Yẹ́ẹ',
    aboutYourself: 'Iya ba iya yẹ-mie-yẹ mọ kẹ́ kária wọi...',
    submitApplication: 'Dịrị Mọ Tóró',
    contactUs: 'Wọi Mọ Fịẹ',
    sendMessage: 'Dịrị-Mẹsigi Tóró',
    yourName: 'Iya Ére',
    subject: 'Fịẹ-ye',
    yourMessage: 'Iya Fịẹ-ye...',
    connectWithUs: 'Wọi Mọ Kẹkẹ',
    callUs: 'Wọi Fọn Mie',
    ourLocations: 'Wọi Wári-ẹẹ',
    factoryOutlet: 'Faktiri ba Wári-ẹẹ',
    quickLinks: 'Bọlọu Dịrị-ẹẹ',
    followUs: 'Wọi Bọlọu Dịrị',
    allRights: 'Kẹmẹ kẹ́mẹ́-yẹ pádịmọ.',
    req1: 'Ẹréba 21 kene miẹ fịẹ',
    req2: 'Ẹbi ID dịrị mie',
    req3: 'Yẹ-mie wári dịrị-ẹẹ',
    req4: 'Bálá-yamọ dẹ́ mie',
    req5: 'Ama-yẹ ẹbị mọ fịẹ',
    req6: 'Kẹmẹ taridịmọ ba ẹbi mie-yẹ',
    ben1: 'Ẹbi púgụ-yama dẹ́',
    ben2: 'Karia ba maktin support',
    ben3: 'Ẹbi amẹ-yamọ kario',
    ben4: 'Dịrị ba yẹ-mie-karia',
    ben5: 'Iya kẹkẹ ama-yẹ mie'
  }, 
  fr: {
    home: 'Accueil',
    about: 'À propos',
    products: 'Produits',
    contact: 'Contact',
    welcome: 'Bienvenue dans Notre Entreprise',
    tagline: 'Nous offrons l\'excellence avec chaque produit',
    explore: 'Explorer les Produits',
    aboutUs: 'À Propos de Nous',
    whoWeAre: 'Qui Nous Sommes',
    whoWeAreText1: 'Nous sommes une équipe passionnée dédiée à offrir l\'excellence dans chaque produit que nous créons. Avec une base solide fondée sur la qualité et la confiance.',
    whoWeAreText2: 'Notre parcours a été façonné par l\'innovation, le travail acharné et un profond engagement envers nos clients.',
    ourMission: 'Notre Mission',
    ourMissionText1: 'Notre mission est de fournir des produits et services exceptionnels qui dépassent les attentes.',
    ourMissionText2: 'Chaque projet que nous entreprenons est une opportunité de créer quelque chose de significatif.',
    meetManagement: 'Rencontrez la Direction',
    ourProducts: 'Nos Produits',
    perItem: 'par article',
    wholesale: 'Vente en Gros',
    wholesaleText: 'Si vous souhaitez acheter en gros, cliquez ici pour obtenir des tarifs spéciaux et des options en volume.',
    bagsProduced: 'Sacs d\'eau produits quotidiennement',
    packsProduced: 'Packs d\'eau ozonisée produits',
    deliveryCoverage: 'De l\'État de Bayelsa couvert en livraison',
    becomeDealer: 'Devenir Revendeur',
    requirements: 'Exigences',
    benefits: 'Avantages',
    dealerApplication: 'Demande de Revendeur',
    fullName: 'Nom Complet',
    phoneNumber: 'Numéro de Téléphone',
    emailAddress: 'Adresse E-mail',
    businessLocation: 'Emplacement de l\'Entreprise / Ville',
    yearsExperience: 'Années d\'Expérience Commerciale',
    aboutYourself: 'Parlez-nous un peu de vous ou de votre entreprise...',
    submitApplication: 'Soumettre la Demande',
    contactUs: 'Contactez-Nous',
    sendMessage: 'Envoyer un Message',
    yourName: 'Votre Nom',
    subject: 'Sujet',
    yourMessage: 'Votre Message...',
    connectWithUs: 'Connectez-vous avec Nous',
    callUs: 'Appelez-Nous',
    ourLocations: 'Nos Emplacements',
    factoryOutlet: 'Usine et Points de Vente',
    quickLinks: 'Liens Rapides',
    followUs: 'Suivez-Nous',
    allRights: 'Tous droits réservés.',
    req1: 'Doit avoir au moins 21 ans',
    req2: 'Pièce d\'identité valide',
    req3: 'Emplacement commercial prouvé ou magasin',
    req4: 'Capacité d\'effectuer un achat initial de produits',
    req5: 'Bonne compréhension du marché local',
    req6: 'Engagement envers la qualité et le service client',
    ben1: 'Tarifs de gros compétitifs',
    ben2: 'Soutien marketing et de marque',
    ben3: 'Approvisionnement fiable en produits',
    ben4: 'Formation et conseils commerciaux',
    ben5: 'Opportunités de territoire exclusif'
  }
}

const LanguageContext = createContext()

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState('en')

  const t = (key) => translations[language][key] || key

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  return useContext(LanguageContext)
}